### ISSUE TITLE
Versioning TaxData

### ISSUE THREAD

**Issue by andersonfrailey** [PSLmodels/taxdata#137]
Spinning off of conversations I've had with @MattHJensen and @hdoupe, we should consider some kind of versioning system for TaxData. There are a couple of reasons this would be helpful:

1. Different users may have different versions of the PUF. As we move to the 2011 PUF, there may be users who have the 2009 PUF and do not want to purchase the 2011 PUF. Similarly, I've been talking to a set of users who have the 2012 PUF and helping them set up TaxData to accommodate that. I believe we should make it easy for them to work with TaxData no matter what year of the PUF they have and this would help.
2. We have been adding a lot of variables to the CPS at the requests of our users. It would be helpful if there was a better way to track the history of the file than having to dig through old PR's and issues.
On point one, my idea for the versioning system would be similar to what we use for Tax-Calculator. We can track major (new PUF or CPS files used in the match), minor (adjusting the weights or growth factors), and patch (adding variables) changes. For example, if we were to version the current PUF, it could be 1.0.0. Then if we were to update to the latest CBO projections, we'll have version 1.1.0. When we update to the 2011 PUF, we will then go to 2.0.0. We can specify in Tax-Calculator and Policy Brain which version we're using.

One of the problems I foresee is supporting multiple versions. If we were to update to the latest CBO projections, we'll want to do that for all versions, not just the latest. @MattHJensen mentioned there may be a relatively efficient way to manage this that involves how we checkout and merge branches. I'm not familiar enough with versioning to talk with any authority on this though and would appreciate other's ideas.

With regards to point two, major changes involve changing the years of the CPS files, minor changes would be reweighing, and patches would be adding variables.

There is an issue with how we handle having both the CPS and PUF files in the same repo though. In my opinion, it would be very difficult and confusing to manage the versions of two files in the same repo, so it might be worth splitting TaxData into two repos. There would be some overlap with the stage one process, but other than that the processes for creating the two are isolated. Or, we could decide that it's not worth versioning the CPS because it's included in the taxcalc package and users likely won't be creating it on there own anyway.

I'm interested in gaining the perspective of others on this. Any opinions regarding the merit of the versioning idea or how to best go about it would be appreciated.

cc @martinholmer @Amy-Xu @GoFroggyRun

**Comment by Amy-Xu** [comment]
Versioning taxdata sounds like a great idea!

>There is an issue with how we handle having both the CPS and PUF files in the same repo though. In my opinion, it would be very difficult and confusing to manage the versions of two files in the same repo, so it might be worth splitting TaxData into two repos. 

My intuition is that this dilemma will happen when a user requires a particular combo of `cps.csv` and PUF. But how often does that happen? I assume people who have puf would lean toward the matched puf, and people who don't would have to use CPS. So we could just use whichever file used more frequently to number the versions.

**Comment by hdoupe** [comment]
@andersonfrailey thanks for opening up this issue.  I think that versioning taxdata is an excellent idea.  However, I'm having trouble coming up with a good way to do this.  It seems like relevant information that each version would need to convey is 

1. Which data set it is used for (i.e. cps or puf)
2. Which year the respective data set was produced
3. Regular versioning for changes after the initial creation

So, right now, taxdata would be on CPS.2013-2015.PUF.2009.0.7.2 (just made up the 0.7.2 part).  Given how complicated this versioning scheme is and that there is little overlap, it makes sense to me to split this repo into taxdata-puf and taxdata-cps.  However, if we can think of an easier way to version then I am open to keeping just one taxdata repo.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> we should consider some kind of versioning system for TaxData

How does this idea relate to the fact that we already have a private repo (which is versioned) to distribute the `puf.csv` file?  And the `cps.csv` file is part of the Tax-Calculator repo which is versioned.  Why exactly do we need more versioning in the taxdata repo?

**Comment by hdoupe** [comment]
I see the taxpuf package and Tax-Calcualtor packages as downstream users of taxdata just like they are downstream users of numpy and numba.  In that respect, I don't think that we need to invent some new way of thinking about versioning in order to version the taxdata repo.

On several occasions, @andersonfrailey and I have taken a deep dive into the pull request and issue history of taxdata to figure out exactly when a specific file was produced.  It would be much easier to point to a specific point in time when taxdata was capable of producing PUF 2012 and CPS 2015 for example.  I think versioning taxdata would help us do that.

**Comment by GoFroggyRun** [comment]
Versioning, or better versioning, taxdata sounds like a good idea in the way that it could help users to provide better citations for their calculations and results. 

In [#1734](https://github.com/open-source-economics/Tax-Calculator/pull/1734), we now suggest users to put "author's calculations" while citing tax-calculator. In fact, a key component is missing: data. If users were using PUF/CPS data prepared by us, it would be a good idea to include the versions of either one in their citations.

**Comment by andersonfrailey** [comment]
@martinholmer asked:
>How does this idea relate to the fact that we already have a private repo (which is versioned) to distribute the puf.csv file? And the cps.csv file is part of the Tax-Calculator repo which is versioned. Why exactly do we need more versioning in the taxdata repo?

I see two benefits for adding versioning for at least the PUF file. 

1. When, for example, we move to the 2011 PUF, users who purchased the 2009 PUF and don't want to upgrade to keep up with us will have an easy way to view and modify the code used in their PUF creation.
2. Along with Tax-Calculator citations, the TaxData version can also be cited. As we've seen each time we update the CBO baselines or change to a new Public Use File/CPS match, the results coming out of Tax-Calculator change. A user can then specify that their result came from Tax-Calculator version x.y.z and TaxData x.y.z when publishing and aid in reproducibility.

Versioning is definitely more useful for those outside our PUF distribution network than those in it and require will more effort on our end, but I think it's worth it.

**Comment by andersonfrailey** [comment]
I'm going to close this to start a fresh discussion on how to version TaxData that won't be lost in the issues tab.
