### ISSUE TITLE
Fix top-coding logic in CPS data preparation

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/taxdata#174]
**In a [comment in Tax-Calculator issue 1658 made on 11/16/2017](https://github.com/open-source-economics/Tax-Calculator/issues/1658#issuecomment-344975203) @andersonfrailey said:**

@martinholmer asked:
> where in the sequence of scripts you list in this `README.md` file are the top-coded replicates added?

This occurs in the `TopCodingV1.sas` script. This is after tax units have been created and adjustments are being made to the final file.

And

> what are your views on the thoughts first expressed by @Amy-Xu that the whole top-coded replicates business is unnecessary for our three (post-2011) CPS files?

I talked with John about this a few months ago. His opinion was that there wasn't a huge need to revise/remove the top coding scripts, though he hadn't run the numbers to verify this.

I'm in favor of at least comparing the results that we would get from removing this part of the creation process. There are two problems preventing this from happening immediately though. First, our SAS license has expired and I just checked and the general AEI one has as well. Second, John hasn't sent me the script to recreate the weights file yet and I haven't completed my work on a python version yet so we can't create a new weights file at this time.

**Comment by martinholmer** [comment]
@andersonfrailey,  I'm going to close [Tax-Calculator issue 1658](https://github.com/open-source-economics/Tax-Calculator/issues/1658) in favor taxdata issue #174.

**Comment by martinholmer** [comment]
@andersonfrailey,  Where do we stand on taxdata issue #174, which seems to me like a bug.

**Comment by martinholmer** [comment]
**Around 3/1/2018 @andersonfrailey said in issue #162:**

No, I haven't been able to put a significant time into considering how to change our top coding procedures yet. Given that the deadline on the UBI project, I think the next version of the CPS should be available after #161 is merged so that Tax-Calculator and then TaxBrain can be updated accordingly.

After that, in no particular order, here are the major changes I have in mind for the CPS file:

- Create the CPS weights file using our own scripts
- Revisit our top coding procedure to address issue #174
- Finish converting the CPS file creation scripts to Python
- Revisit how n24 is calculated to address issue #157
- Address missing variables in the CPS pointed out in #119
- Add testing scripts to the repo

**Comment by andersonfrailey** [comment]
Closing now that we've switched to python scripts to create the CPS.
