### ISSUE TITLE
Remove special handling of CPS top-coding

### ISSUE THREAD

**Issue by lucassz** [PSLmodels/taxdata#253]
The current method employed by TaxData to handle CPS top-coding is to augment the topcode by a randomly chosen value, with this process repeated a number of times while keeping the weight of the individual tax entry constant. [CPS 2015](http://www.nber.org/cps/cpsmar2015.pdf) uses a different method of swapping values between different but similar households ("rank proximity swapping"), supposedly minimizing the differences in the statistical distribution and to possible calculations from the dataset. This should eliminate the need for TaxData to do the detailed handling of top-coding it does now.

@andersonfrailey

**Comment by martinholmer** [comment]
@lucassz,  Is the topic in your issue #253 different than the topic raised in issue #174?

**Comment by andersonfrailey** [comment]
@martinholmer it's in line with the discussion in #174. I asked @lucassz to look into how we should revise our top coding logic and he found that there no longer seems to be a need for any top coding adjustments.

**Comment by andersonfrailey** [comment]
Closing now that we've switched to python scripts to create the CPS.
