### ISSUE TITLE
Python CPS Repo

### ISSUE THREAD

**Issue by andersonfrailey** [PSLmodels/taxdata#286]
I forgot that I had set up a repository where I could work on the Python scripts to create the CPS file. That repository can be found [here](https://github.com/andersonfrailey/cpstaxunits) if you would like to follow along. Right now, everything runs, but I haven't been able to completely replicate what is produced by the SAS files, which in theory I should be able to do at least to the top coding adjustments where there is some randomization. I'm open to any feedback/bug fixes for the work I've done so far.

cc @Amy-Xu @martinholmer @MattHJensen @hdoupe

**Comment by MaxGhenis** [comment]
Is https://github.com/andersonfrailey/cpstaxunits still the repo for CPS tax units? The latest commit there is from October 2018.

**Comment by andersonfrailey** [comment]
@MaxGhenis, I would ignore that repo. It dates back to when I was trying to exactly reproduce the SAS scripts to create the CPS. As has been mentioned in conversation before, that never worked out and I've since started to try and create the tax units from scratch. I haven't pushed that to GitHub yet, but I'll post a link when I do.

In the meantime, I'm going to close this issue so that people don't stumble onto that link.
