### ISSUE TITLE
What does XTOT==0 in PUF mean?

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/taxdata#303]
Just noticed this and wasn't sure how to interpret it.

![image](https://user-images.githubusercontent.com/6076111/52888538-e44db580-3130-11e9-8333-0e816ef92ee8.png)

**Comment by andersonfrailey** [comment]
@MaxGhenis, in the raw PUF, XTOT is the sum of all exemptions claimed. So if XTOT is zero that unit didn't claim any exemptions. An example of this would be a filer who was also being claimed as a dependent and thus couldn't claim the personal exemption and has no other reason to claim an exemption.

**Comment by MaxGhenis** [comment]
Thanks for the example. Is there logic you'd recommend to approximate the number of "people" in the tax units, e.g. comparable to people in CPS households? Would `ceiling(XTOT, 1)` be best?

I'm summarizing the number of people helped/hurt by different reforms, and don't want to discard these tax units.

**Comment by andersonfrailey** [comment]
@MaxGhenis, I would say that `max(XTOT, 1)` is your best bet. Unfortunately XTOT is the closest we have to a count of people in a tax unit. Also keep in mind that XTOT is top coded in the PUF so it's possible that any summary depending on the PUF would undercount the number of people affected by a reform.

**Comment by MaxGhenis** [comment]
Thanks @andersonfrailey

**Comment by MaxGhenis** [comment]
We can discuss more in https://github.com/PSLmodels/taxdata/issues/149, but would you recommend `max(XTOT, 1)` over `nu18+n1820+n21` for estimating the total number of people while they don't match?
