### ISSUE TITLE
Question about data_source variable in puf.csv file

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/taxdata#315]
@andersonfrailey,  I'm confused about the meaning of the `data_source` variable in the `puf.csv` file.  I expected that a value of 1 indicated that the record was from the IRS-SOI PUF and that a value of 0 indicated that the record was from the CPS.  But that doesn't appear to be the case.  Yesterday, @donboyd5 and I exchanged quite a few emails and here is what we found (I'm showing Don's R tabulations, but I get exactly the same `puf.csv` results with a one-line AWK program):

<img width="912" alt="Screen Shot 2019-06-04 at 2 22 11 PM" src="https://user-images.githubusercontent.com/12170745/58904389-67414e80-86d5-11e9-8fed-ea9d8132dfa8.png">

<img width="893" alt="Screen Shot 2019-06-04 at 2 25 08 PM" src="https://user-images.githubusercontent.com/12170745/58904398-6c060280-86d5-11e9-8795-78754e304e78.png">

What am I missing?  
Why isn't the record count in the `puf.csv` file for `data_source==1` equal to 163786?

**Comment by MaxGhenis** [comment]
Is this because records are duplicated during certain imputation processes?

**Comment by andersonfrailey** [comment]
@MaxGhenis is mostly correct. He's right that records are duplicated, but this occurs during the statistical matching process in the PUF. It's the CPS where certain records are duplicated in the imputation process.

**Comment by martinholmer** [comment]
@andersonfrailey and @MaxGhenis,  Thanks for the explanation.
