### ISSUE TITLE
715 records in the PUF have n65>n21

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/taxdata#318]
Defining n65 as `(age_head>64) + (age_spouse>64) + elderly_dependents`, 715 records have `n65>n21`. All 715 have `age_head>64`, and they otherwise fall into 3 categories ([notebook](https://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/random/people_per_tax_unit.ipynb)):
1. 700 records have `n21=1` and `age_spouse>64`, e.g. RECID 415.
2. 13 records have `n21=2`, `age_spouse>64`, and `elderly_dependents=1`, e.g. RECID 6869.
3. 2 records have `n21=1`, and `elderly_dependents=1`, e.g. RECID 13275.

**Comment by MaxGhenis** [comment]
Was this addressed in recent updates?

**Comment by andersonfrailey** [comment]
@MaxGhenis, yep this has been resolved with the latest updates. Closing.
