### ISSUE TITLE
Why do 5k records in the CPS tax file have no adults?

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/taxdata#321]
5,446 records in the CPS tax file, which together represent 2.05M tax units and 2.10M people, have `n1820+n21=0` ([notebook](https://colab.research.google.com/drive/11u3rtf66j4oFVb7W0xw8tYvNITm4r05M)). That's about 3% of children, and for comparison, [4-5%](https://www.census.gov/content/dam/Census/library/visualizations/time-series/demo/families-and-households/ch-1.pdf) of kids live without their parents (though presumably many live with other adults like grandparents). That seems high to me.

Before looking through the CPS microdata to see the prevalence of zero-adult households, I was curious if anyone happened to know if this is a result of the tax unit creation process, and if it's an intended one. @andersonfrailey do you know if your new Python approach would split out a child from its adult-including household as its own tax unit?

**Comment by codykallen** [comment]
@MaxGhenis, I've encountered this previously. I believe it's occurring for tax planning purposes among families with teenage children. 

Specifically, suppose you are in the 35% bracket, and that you have a teenager with a part-time or summer job, who has $10,000 of income. Under pre-TCJA law, the best tax planning strategy would have the teenager file separately, which would put him at the 10% marginal rate on very little income. Meanwhile, the parent would claim the teenager as a dependent, and thus taking the teenager's personal exemption, which is worth more at a higher tax rate. 

Under TCJA law, there is no longer a personal exemption for the parent to claim, but the family is still better off having the teenager file separately.

**Comment by MaxGhenis** [comment]
Thanks @codykallen. I also confirmed that zero-adult households are rare in the CPS itself ([notebook](https://nbviewer.jupyter.org/github/MaxGhenis/random/blob/master/cps_zero_adult_households.ipynb)), totaling roughly a dozen survey households representing no more than ~23k people in a given year:
![table of total people and zero-adult-HH people by year](https://user-images.githubusercontent.com/6076111/60904194-7745d400-a227-11e9-90fc-d0a8a01182af.png)

This answers my question.
