### ISSUE TITLE
Pull contents of PR 314 (create CPS file with scripts)

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/taxdata#341]
This is a bit ridiculous, but #314's comment volume may have broken GitHub. There was some useful information there, so if anyone gets it to load, could you please expand all the comments and print it to a PDF so we can refer to it later?

**Comment by andersonfrailey** [comment]
[taxdata314.pdf](https://github.com/PSLmodels/taxdata/files/4904952/taxdata314.pdf)
Here you go, @MaxGhenis. I'm a little proud that we broke GitHub tbh.
