### ISSUE TITLE
Replacing nu05 with nu06 in CPS and PUF

### ISSUE THREAD

**Issue by Peter-Metz** [PSLmodels/taxdata#347]
Based on #329 and #314, it seems that the most recent versions of the PUF and CPS both have the `nu06` variable. However, Tax-Calculator does not recognize `nu06` as a valid Records variable (see [records_variables.json](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/records_variables.json)) because the newest versions of the PUF and CPS have not yet been disseminated.

I wanted to open this issue to continue the conversation in #329 and come up with a plan to bring Tax-Calculator up to speed with Tax-Data.

cc @andersonfrailey @MattHJensen

**Comment by MattHJensen** [comment]
Thanks Peter, what do you think about:

- Open PR-1 to Tax-Calculator w new PUF and CPS as of merge of #314 (including nu06 from #329). 
- Open PR-2 to Tax-Calculator w new PUF and CPS from #332, building off of PR1 branch rather than master.
- Merge PR-1 and then PR-2.

**Comment by Peter-Metz** [comment]
@MattHJensen the general plan sounds good. It might be easier to do the PUF/CPS update in one PR from a Tax-Calc testing standpoint, but I'm not sure.

@MattHJensen or @andersonfrailey: would you mind advising me on how to generate a new puf.csv?

**Comment by andersonfrailey** [comment]
@Peter-Metz, all you'll need to do is drop the raw PUF file `puf2011.csv` and a CSV version of the 2016 CPS file (I can send you that if you need it) in the `puf_data/StatMatch/Matching` directory, then you can just use `make all` or `make puf-files` from the top of the directory.

**Comment by Peter-Metz** [comment]
Thanks @andersonfrailey! Is the CPS file called `cpsmar2016.csv`? If so, I have everything I need.

**Comment by andersonfrailey** [comment]
@Peter-Metz yep that's the one!

**Comment by andersonfrailey** [comment]
This has been taken care of. Closing.
