### ISSUE TITLE
Broken link to StatMatch subdirectory

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/taxdata#374]
[This](https://github.com/PSLmodels/taxdata/tree/master/taxdata/puf) taxdata page contains a [broken link](https://github.com/PSLmodels/taxdata/blob/master/taxdata/puf/StatMatch/README.md) to the  StatMatch subdirectory.

It looks like the correct link probably is [this](https://github.com/PSLmodels/taxdata/tree/master/taxdata/matching).

**Comment by andersonfrailey** [comment]
Thanks for reporting this, @donboyd5! Fixed in #376
