### ISSUE TITLE
make puf-files gives: "make puf-files make: *** No rule to make target 'data/cps-matched-puf.csv', needed by 'data/puf.csv'.  Stop."

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/taxdata#380]
make puf-files gives:

"make puf-files make: *** No rule to make target 'data/cps-matched-puf.csv', needed by 'data/puf.csv'.  Stop."

The old rule, commented out in Makefile, is:

```
# PM_DIR=./puf_data/StatMatch/Matching
# PM_PY_FILES := $(shell ls -l $(PM_DIR)/*py | awk '{print $$9}')
# data/cps-matched-puf.csv: $(PM_PY_FILES) \
#                               $(PM_DIR)/puf2011.csv \
#                               $(PM_DIR)/cpsmar2016.csv
# 	cd $(PM_DIR) ; python runmatch.py
```

Maybe I should update folder names and program names and uncomment it? It looks like it is expecting cpsmar2016.csv but I am not sure which csv file that should be.

Many thanks for any advice.

**Comment by andersonfrailey** [comment]
Thanks for flagging this @donboyd5. Working on a fix now
