### ISSUE TITLE
Code style improvement

### ISSUE THREAD

**Issue by bodiyang** [PSLmodels/taxdata#422]
after running 'make cstest', many code style issues appear need to be solved (e.g. line too long)

**Comment by jdebacker** [comment]
How about using [Black](https://black.readthedocs.io/en/stable/) to automate the code formatting?  A GH Action test can be set to ensure contributors keep the code style consistent.

Bodi - would you be ok with that?  If so, I can make changes in a way they won't contaminate the whole git blame.

**Comment by bodiyang** [comment]
> How about using [Black](https://black.readthedocs.io/en/stable/) to automate the code formatting? A GH Action test can be set to ensure contributors keep the code style consistent.
> 
> Bodi - would you be ok with that? If so, I can make changes in a way they won't contaminate the whole git blame.

Yes Jason, I'll open a PR on this later
