### ISSUE TITLE
2033 puf weights and puf ratio odd results

### ISSUE THREAD

**Issue by bodiyang** [PSLmodels/taxdata#427]
Issue:
The updated [puf weights](https://github.com/PSLmodels/taxdata/blob/master/puf_stage2/puf_weights.csv.gz) and [puf ratio](https://github.com/PSLmodels/taxdata/blob/master/puf_stage3/puf_ratios.csv) from [the recent CBO update](https://github.com/PSLmodels/taxdata/pull/421) look odd. There is an inconsistency between the value in 2033 and the previous years before 2032 

Traceback:
The input files to generate PUF weight in [PUF STAGE II](https://github.com/bodiyang/taxdata/tree/0f7bbe7ac704be7140da4deda19cbd8094994b9c/puf_stage2),  [Stage I factors](https://github.com/PSLmodels/taxdata/blob/master/puf_stage1/Stage_I_factors.csv) and [Stage II targets](https://github.com/PSLmodels/taxdata/blob/master/puf_stage1/Stage_II_targets.csv) all look ok, there is not a noticeable gap between 2033 and the years before.

PS: The [CPS weights](https://github.com/PSLmodels/taxdata/blob/master/cps_stage2/cps_weights.csv.gz) looks ok. 

As a result, the iitax and other calculated projections look fine with CPS but suspicious with PUF. I produced a multi year projections, at [taxdata_report_2023-05-24.pdf](https://github.com/PSLmodels/taxdata/files/11555963/taxdata_report_2023-05-24.pdf). The projections can be found in "Validation" section, for both CPS and PUF based calculations. The 2033 PUF projection values diff a lot from the years before 2032.

@jdebacker @MattHJensen @andersonfrailey

**Comment by bodiyang** [comment]
some examples of puf weights:
WT2011,WT2012,WT2013,WT2014,WT2015,WT2016,WT2017,WT2018,WT2019,WT2020,WT2021,WT2022,WT2023,WT2024,WT2025,WT2026,WT2027,WT2028,WT2029,WT2030,WT2031,WT2032,WT2033
147096,146655,149097,148523,202525,197670,224338,227857,230929,233659,236410,239055,241743,244451,247181,249954,252748,255585,258443,261323,264266,267285,186356141932,141506,143862,193467,195414,190730,216462,219858,222821,225455,228110,230662,233255,235869,238503,241179,243875,246612,249369,252148,254988,258017,179814
39425,39307,39961,39807,54281,52980,60127,61071,61894,62625,63363,64072,64792,65518,66250,66993,67742,68502,69268,70040,70829,71712,49947
51269,51115,51966,51766,35559,37098,29659,30124,30530,30891,31255,31604,31960,32318,32679,33045,33415,33790,34168,34548,34937,35288,64953

**Comment by bodiyang** [comment]
Current investigation status: This issue is likely caused by the [tolerance value](https://github.com/PSLmodels/taxdata/blob/master/puf_stage2/solver.jl) line 86.

The current tolerance value 0.45 does not seem good anymore. After set the value as 0.6 (as an example), the projections of 2033 significantly improved and basically match with the CBO projections.

Still in work to find the best tolerance value.

A question: what would be the cost of enlarge the tolerance value?   --- thought in my mind: computational load/speed, and others?

**Comment by bodiyang** [comment]
Current investigation status: 

I believe this issue is associated with the optimization [tolerance](https://github.com/PSLmodels/taxdata/blob/master/puf_stage2/solver.jl)

The 2033 projections, PUF ratios, weightings are odd under the current tolerance of 0.45. 

I reset the tolerance value as 0.5 and find the corresponding results to be satisfying, with 2033 projections consistent with the years before and match with the CBO projections.

I'm still working on to find the best tolerance value. Any suggestions on the criteria of selecting tolerance value? 
And what would the cost of enlarging the tolerance value?  -- in my mind, computation load/speed might be one factor.

**Comment by jdebacker** [comment]
@bodiyang What do the projections look like with the 0.5 tolerance value?

cc @donboyd5 @andersonfrailey

**Comment by bodiyang** [comment]
This is some projection values of **CBO projections**, **TaxData with tolerance of 0.5** and **TaxData with tolerance of 0.45**

Salaries and Wages: 15488;  15304;  17464
Taxable interest and ordinary dividends (excludes qualified dividends): 445;  398;  501
Qualified dividends: 420;  390;  516
Capital gain or loss: 1491;  1045;  1503
Net business income (all income and loss reported on Schedules C, E, and F): 2107;  2110;  2434
Taxable pensions and annuities and IRA distributions: 2053;  2475;  3132
Taxable Social Security benefits:  1003;  905;  1026
Total income: 22822;  23123;  27114
Subtract Statutory adjustments: 258;  248;  294
Adjusted gross income: 22564;  22875;  27114

**Comment by bodiyang** [comment]
This is the projection value with the tolerance value of 0.5. PUF projections start from page 26 [updated -- 0dot 5.pdf](https://github.com/PSLmodels/taxdata/files/11637770/updated.--.0dot.5.pdf)

**Comment by bodiyang** [comment]
fixed in [PR 429](https://github.com/PSLmodels/taxdata/pull/429)
